name: realtime-inventory-dashboard
lang: unknown
lang_version: unknown
git:
  enable: true
codeowners:
  enable: true
renovatebot:
  enable: true
  automerge:
    enable: true
semaphore:
  enable: true
